include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  errors:
    depend_on_referenced_packages: ignore
    unused_import: warning
    avoid_print: warning
    invalid_null_aware_operator: warning
    dead_null_aware_expression: warning

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_classes_with_only_static_members: true
    avoid_positional_boolean_parameters: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_relative_lib_imports: true
    always_use_package_imports: true
    use_super_parameters: true
    prefer_single_quotes: true
