import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:goal_master_admin/core/styles/app_colors.dart';
import 'package:goal_master_admin/core/styles/app_text_styles.dart';
import 'package:goal_master_admin/core/utils/arabic_dates.dart';
import 'package:goal_master_admin/features/booking/data/model/series_preview.dart';

/// Move one appointment of a recurring booking.
///
/// Deliberately about a single week and nothing else: the manager is not
/// rebuilding the series, they are answering "this one Sunday is taken — when
/// instead?". Everything offered here came from the server, generated by the
/// venue's own replacement rules; the sheet neither computes availability nor
/// lets an arbitrary time be typed in.
///
/// The chosen slot REPLACES this week. It never becomes a fifth appointment.
Future<ReplacementSlot?> showChangeAppointmentSheet(
  BuildContext context, {
  required PreviewDate date,
}) {
  final options = date.replacementOptions;

  return showModalBottomSheet<ReplacementSlot>(
    context: context,
    isScrollControlled: true,
    backgroundColor: Colors.transparent,
    builder: (sheetContext) => Directionality(
      textDirection: TextDirection.rtl,
      child: Container(
        constraints: BoxConstraints(
          maxHeight: MediaQuery.of(sheetContext).size.height * 0.82,
        ),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.vertical(top: Radius.circular(24.r)),
        ),
        child: SafeArea(
          top: false,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              _handle(),
              Padding(
                padding: EdgeInsets.fromLTRB(20.w, 4.h, 20.w, 0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'تغيير موعد ${_shortLabel(date)}',
                      style: AppTextStyles.font18Bold
                          .copyWith(color: AppColors.uiBlack),
                    ),
                    SizedBox(height: 6.h),
                    Text(
                      'الموعد الأصلي ${_originalTime(date)} غير متاح.\n'
                      'اختر موعداً بديلاً لهذا الأسبوع.',
                      style: AppTextStyles.font14Regular
                          .copyWith(color: AppColors.fontColor),
                    ),
                    SizedBox(height: 16.h),
                  ],
                ),
              ),
              Flexible(
                child: (options == null || !options.hasAny)
                    ? _empty()
                    : ListView(
                        padding: EdgeInsets.fromLTRB(20.w, 0, 20.w, 20.h),
                        shrinkWrap: true,
                        children: [
                          // Same evening first: keeping the day is usually
                          // what a venue and its customer both want.
                          if (options.sameDay.isNotEmpty) ...[
                            _groupLabel(_sameDayLabel(date)),
                            SizedBox(height: 8.h),
                            ...options.sameDay.map((slot) => _OptionTile(
                                  slot: slot,
                                  onTap: () =>
                                      Navigator.pop(sheetContext, slot),
                                )),
                            SizedBox(height: 18.h),
                          ],
                          if (options.nearbyDays.isNotEmpty) ...[
                            _groupLabel('أيام قريبة'),
                            SizedBox(height: 8.h),
                            ...options.nearbyDays.map((slot) => _OptionTile(
                                  slot: slot,
                                  showDate: true,
                                  onTap: () =>
                                      Navigator.pop(sheetContext, slot),
                                )),
                          ],
                        ],
                      ),
              ),
            ],
          ),
        ),
      ),
    ),
  );
}

Widget _handle() => Center(
      child: Container(
        width: 40,
        height: 4,
        margin: const EdgeInsets.symmetric(vertical: 12),
        decoration: BoxDecoration(
          color: const Color(0xFFDDDDDD),
          borderRadius: BorderRadius.circular(2),
        ),
      ),
    );

Widget _groupLabel(String text) => Builder(
      builder: (context) => Text(
        text,
        style: AppTextStyles.font14SemiBold.copyWith(color: AppColors.fontColor),
      ),
    );

Widget _empty() => Builder(
      builder: (context) => Padding(
        padding: EdgeInsets.fromLTRB(20.w, 10.h, 20.w, 40.h),
        child: Column(
          children: [
            Icon(Icons.event_busy_outlined,
                size: 34.w, color: AppColors.fontColor),
            SizedBox(height: 12.h),
            Text('لا توجد مواعيد بديلة لهذا الأسبوع',
                textAlign: TextAlign.center,
                style:
                    AppTextStyles.font16Bold.copyWith(color: AppColors.uiBlack)),
            SizedBox(height: 6.h),
            Text('جرّب وقتاً مختلفاً للحجز الشهري من البداية.',
                textAlign: TextAlign.center,
                style: AppTextStyles.font14Regular
                    .copyWith(color: AppColors.fontColor)),
          ],
        ),
      ),
    );

String _shortLabel(PreviewDate date) {
  final start = date.startAt;
  return start != null ? arabicShortDateOf(start) : date.date;
}

String _originalTime(PreviewDate date) {
  final start = date.startAt;
  return start != null ? arabicSlotClock(start) : date.startTime;
}

String _sameDayLabel(PreviewDate date) {
  final start = date.startAt;
  return start != null ? arabicDayAndDateOf(start) : date.date;
}

class _OptionTile extends StatelessWidget {
  const _OptionTile({
    required this.slot,
    required this.onTap,
    this.showDate = false,
  });

  final ReplacementSlot slot;
  final VoidCallback onTap;
  final bool showDate;

  @override
  Widget build(BuildContext context) {
    final start = slot.startAt;
    final end = slot.endAt;

    return Padding(
      padding: EdgeInsets.only(bottom: 8.h),
      child: InkWell(
        borderRadius: BorderRadius.circular(12.r),
        onTap: onTap,
        child: Container(
          constraints: BoxConstraints(minHeight: 56.h),
          padding: EdgeInsets.symmetric(horizontal: 14.w, vertical: 12.h),
          decoration: BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.circular(12.r),
            border: Border.all(color: AppColors.primaryBlueLight),
          ),
          child: Row(
            children: [
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    if (showDate) ...[
                      Text(
                        start != null
                            ? arabicDayAndDateOf(start)
                            : slot.dateLabel,
                        style: AppTextStyles.font12Regular
                            .copyWith(color: AppColors.fontColor),
                      ),
                      SizedBox(height: 2.h),
                    ],
                    Text(
                      start != null && end != null
                          ? arabicRange(start, end)
                          : slot.timeLabel,
                      style: AppTextStyles.font16Bold
                          .copyWith(color: AppColors.uiBlack),
                    ),
                  ],
                ),
              ),
              // Shown only when the venue prices this slot differently from
              // the rest — otherwise it is noise on every row.
              if (slot.price > 0)
                Text('${slot.price.toStringAsFixed(0)} د.ل',
                    style: AppTextStyles.font14Regular
                        .copyWith(color: AppColors.fontColor)),
              SizedBox(width: 8.w),
              Icon(Icons.chevron_left, size: 20.w, color: AppColors.primary),
            ],
          ),
        ),
      ),
    );
  }
}
